name: mybooking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  book_my_seat: ^1.0.1
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.2.0
  provider: ^6.1.1
  syncfusion_flutter_datepicker: ^24.2.6
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/
  - assets/icons/
  - assets/fonts/